// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	endpoint "get_add/pkg/endpoint"
	pb "get_add/pkg/grpc/pb"
	grpc "github.com/go-kit/kit/transport/grpc"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	add grpc.Handler
	pb.UnimplementedGetAddServer
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.GetAddServer {
	return &grpcServer{add: makeAddHandler(endpoints, options["Add"])}
}
