// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: github.com/zqf960928/getadd/pkg/grpc/pb/get_add.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A int32 `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B int32 `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_get_add_pkg_grpc_pb_get_add_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_get_add_pkg_grpc_pb_get_add_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_get_add_pkg_grpc_pb_get_add_proto_rawDescGZIP(), []int{0}
}

func (x *AddRequest) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *AddRequest) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

type AddReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res int32 `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *AddReply) Reset() {
	*x = AddReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_get_add_pkg_grpc_pb_get_add_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReply) ProtoMessage() {}

func (x *AddReply) ProtoReflect() protoreflect.Message {
	mi := &file_get_add_pkg_grpc_pb_get_add_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReply.ProtoReflect.Descriptor instead.
func (*AddReply) Descriptor() ([]byte, []int) {
	return file_get_add_pkg_grpc_pb_get_add_proto_rawDescGZIP(), []int{1}
}

func (x *AddReply) GetRes() int32 {
	if x != nil {
		return x.Res
	}
	return 0
}

var File_get_add_pkg_grpc_pb_get_add_proto protoreflect.FileDescriptor

var file_get_add_pkg_grpc_pb_get_add_proto_rawDesc = []byte{
	0x0a, 0x21, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x28, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x01, 0x61, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01,
	0x62, 0x22, 0x1c, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x73, 0x32,
	0x2d, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x12, 0x23, 0x0a, 0x03, 0x41, 0x64, 0x64,
	0x12, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x15,
	0x5a, 0x13, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_get_add_pkg_grpc_pb_get_add_proto_rawDescOnce sync.Once
	file_get_add_pkg_grpc_pb_get_add_proto_rawDescData = file_get_add_pkg_grpc_pb_get_add_proto_rawDesc
)

func file_get_add_pkg_grpc_pb_get_add_proto_rawDescGZIP() []byte {
	file_get_add_pkg_grpc_pb_get_add_proto_rawDescOnce.Do(func() {
		file_get_add_pkg_grpc_pb_get_add_proto_rawDescData = protoimpl.X.CompressGZIP(file_get_add_pkg_grpc_pb_get_add_proto_rawDescData)
	})
	return file_get_add_pkg_grpc_pb_get_add_proto_rawDescData
}

var file_get_add_pkg_grpc_pb_get_add_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_get_add_pkg_grpc_pb_get_add_proto_goTypes = []interface{}{
	(*AddRequest)(nil), // 0: pb.AddRequest
	(*AddReply)(nil),   // 1: pb.AddReply
}
var file_get_add_pkg_grpc_pb_get_add_proto_depIdxs = []int32{
	0, // 0: pb.GetAdd.Add:input_type -> pb.AddRequest
	1, // 1: pb.GetAdd.Add:output_type -> pb.AddReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_get_add_pkg_grpc_pb_get_add_proto_init() }
func file_get_add_pkg_grpc_pb_get_add_proto_init() {
	if File_get_add_pkg_grpc_pb_get_add_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_get_add_pkg_grpc_pb_get_add_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_get_add_pkg_grpc_pb_get_add_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_get_add_pkg_grpc_pb_get_add_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_get_add_pkg_grpc_pb_get_add_proto_goTypes,
		DependencyIndexes: file_get_add_pkg_grpc_pb_get_add_proto_depIdxs,
		MessageInfos:      file_get_add_pkg_grpc_pb_get_add_proto_msgTypes,
	}.Build()
	File_get_add_pkg_grpc_pb_get_add_proto = out.File
	file_get_add_pkg_grpc_pb_get_add_proto_rawDesc = nil
	file_get_add_pkg_grpc_pb_get_add_proto_goTypes = nil
	file_get_add_pkg_grpc_pb_get_add_proto_depIdxs = nil
}
